// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axuwfojlpktofkilxcky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4dXdmb2pscGt0b2ZraWx4Y2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTI2MDIsImV4cCI6MjA1Nzc2ODYwMn0.X7XcJvPqF72bmnCnV4RrV5sL8Q4lOSAfCwrb5MT4Xbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);